version: 2

jobs:
  deploy-prod:
    docker:
      - image: circleci/php:cli
    working_directory: ~/laravel 
    steps:
      - run:
          name: SSH and deploy
          command: ssh -oStrictHostKeyChecking=no ops@51.158.72.176 -p 19090 "cd /home/ops/docker-build/pmi-webui-prod && sh deploy.sh ${CIRCLE_TAG}"
  deploy-staging:
    docker:
      - image: circleci/php:cli
    working_directory: ~/laravel 
    steps:
      - run:
          name: SSH and deploy
          command: ssh -oStrictHostKeyChecking=no ops@51.158.72.176 -p 19090 "cd /home/ops/docker-build/pmi-webui-staging && sh deploy.sh master"
  deploy-develop:
    docker:
      - image: circleci/php:cli
    working_directory: ~/laravel 
    steps:
      - run:
          name: SSH and deploy
          command: ssh -oStrictHostKeyChecking=no ops@51.158.72.176 -p 19090 "cd /home/ops/docker-build/pmi-webui-develop && sh deploy.sh develop"      
workflows:
  version: 2
  build_and_deploy_develop:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only: develop
  build_and_deploy_staging:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only: master
  build_and_deploy_prod:
    jobs:
      - hold:
          type: approval
          filters:
            tags:
              only: /^v.*/
      - deploy-prod:
          requires:
            - hold
          filters:
            tags:
              only: /^v.*/